### ISSUE TITLE
Billing and shipping address.

### ISSUE THREAD

**Issue by jariwalabhavesh** [smarkets/react-native-paypal#12]
Can we pass billing and shipping address externally to PayPal? Means I had a seperate screen to get the shipping address user will enter the shipping address there and I want to send these address to Paypal. Is it possible?

Or PayPal has its own interface to collect billing and shipping address. 

Do this library support billing address and shipping address?

**Comment by riso** [comment]
Hi, we currently don't support this, but looking at Braintree iOS docs (https://braintree.github.io/braintree_ios/Classes/BTPayPalRequest.html#/c:objc(cs)BTPayPalRequest(py)shippingAddressOverride) it seems like it's possible to add this feature. I assume Braintree for Android supports a similar API too. 
We won't be adding it in the near future, but we're happy to look at a PR if you're willing to add this.

**Comment by dkfl1995** [comment]
@riso and others. Hi!
I will provide shipping address feature PR at ongoing holidays. Hope y'all will taste it.
