### ISSUE TITLE
braintreeFragment.addListener error : BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app

### ISSUE THREAD

**Issue by iwmdipak** [smarkets/react-native-paypal#14]
requestOneTimePayment call but not open paypal screen

**Comment by riso** [comment]
hi. have you rebuilt your native code after following the instructions provided in the readme?

if you open your AndroidManifest in Android Studio, in the Merged Manifest tab, you should find a section like the following one

![image](https://user-images.githubusercontent.com/448304/57855904-af123b80-77e3-11e9-9e20-1daec821bee6.png)

could you please confirm it's there?

**Comment by riso** [comment]
I'll close this, feel free to re-open if you still experience issues.

**Comment by iwmdipak** [comment]
![Screenshot 2019-05-23 at 3 46 52 PM](https://user-images.githubusercontent.com/48380809/58245303-172bc900-7d72-11e9-866d-85b3a651d1bb.png)

**Comment by iwmdipak** [comment]
i have already add activity please check my screen short

**Comment by riso** [comment]
you shouldn't need to add that section in you AndroidManifest manually, but if you open the Merged Manifest tab in android studio it should show there. does it?
