### ISSUE TITLE
BraintreeCore.h file not found

### ISSUE THREAD

**Issue by reactNativeDevelope** [smarkets/react-native-paypal#16]
![Screen Shot 2019-05-31 at 3 45 08 PM](https://user-images.githubusercontent.com/51231540/58699899-49fe3e80-83bc-11e9-9240-b63025fb4a3e.png)

**Comment by reactNativeDevelope** [comment]
![Screen Shot 2019-05-31 at 3 45 08 PM](https://user-images.githubusercontent.com/51231540/58699899-49fe3e80-83bc-11e9-9240-b63025fb4a3e.png)

**Comment by riso** [comment]
Hi. have you followed the readme? Could you please post the content of your Podfile?

**Comment by riso** [comment]
Closing this now, feel free to re-open if you still have issues.

**Comment by ankitgauravapporio** [comment]
hello @riso  i am using these 
 "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-paypal": "^2.0.4"
  },
and getting the same error BraintreeCore.h file not found 
can you please help me out on this, thank you
