### ISSUE TITLE
can i use this package  for subscription base payment?

### ISSUE THREAD

**Issue by shaikhaffan** [smarkets/react-native-paypal#23]

**Comment by riso** [comment]
Hey, sorry for the late reply. We never implemented support for recurring payments. It is possible to add that feature though, and we would be happy to accept a PR adding it.

**Comment by Mavenic** [comment]
Does it support authorization for future payments?

**Comment by nzankich** [comment]
@Mavenic This library doesn't support future payments either but I believe recurring payment integration would cover that 
see https://developers.braintreepayments.com/guides/recurring-billing/overview

**Comment by nzankich** [comment]
lmk if this doesn't work and I can open a feature request to add this
