### ISSUE TITLE
Does this library support checking out with debit or credit while not logged in?

### ISSUE THREAD

**Issue by ZChenzy** [smarkets/react-native-paypal#27]
Would be nice to have an example app!

**Comment by riso** [comment]
Hey, currently the only flow implemented in the library is the Checkout flow, which requires users to have a PayPal account and login to it (more info here: https://developers.braintreepayments.com/guides/paypal/overview/ios/v4).

As for the example app, it's a good idea! While we don't have any plan at the moment to add one, we would welcome a PR that implements it.
