### ISSUE TITLE
Getting Error: Error requesting one time payment

### ISSUE THREAD

**Issue by Openappdev** [smarkets/react-native-paypal#29]
Hi,
Firsty, thanks for this library.

I'm in sandbox environment. After getting client token from my server, I'm getting this error when processing requestOneTimePayment => **Error: Error requesting one time payment**.

Here is my code : 
`    try {

      const token =  await PayPalService.getClientToken();
      const {
        nonce,
        payerId,
        email,
        firstName,
        lastName,
        phone 
      } = await requestOneTimePayment(
        token,
        {
          amount: '5', // required
          // any PayPal supported currency (see here: https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments)
          currency: 'USD',
          // any PayPal supported locale (see here: https://braintree.github.io/braintree_ios/Classes/BTPayPalRequest.html#/c:objc(cs)BTPayPalRequest(py)localeCode)
          localeCode: 'en_US', 
          shippingAddressRequired: false,
          userAction: 'commit', // display 'Pay Now' on the PayPal review page
          // one of 'authorize', 'sale', 'order'. defaults to 'authorize'. see details here: https://developer.paypal.com/docs/api/payments/v1/#payment-create-request-body
          intent: 'authorize', 
        }
      );
      console.log('nonce : '+nonce);
      console.log('payerId : '+payerId);
      
    } catch (error) {
      console.log('error : '+error);
    }`

Please any help ?
Thanks.

**Comment by ShaBax** [comment]
Same issue , got any solution ? 
```
Error: Error requesting one time payment
    at fn (NativeModules.js:99)
    at _callee$ (VM5 PaymentCheckoutScreen.bundle:122)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
    at core.js:123
```

**Comment by ShaBax** [comment]
I think the problem is with the token you are using. Try to print the error you are getting you will get more info about the problem. 

In my case, it was the token (merchant not found). Try to use the token from this URL [Create Token](https://braintree-sample-merchant.herokuapp.com/client_token)

If you don't get any error by using this token then the problem is with your token, It means your Braintree account is not connected with your PayPal account. 

The solution is to link PayPal with your Braintree account  [How to link ](https://help.paperform.co/en/articles/2072845-how-to-connect-braintree-your-paperform-account-and-paypal)

**Comment by Openappdev** [comment]
Hi @ShaBax, Thanks for detailed feedback and the time you took for all that, really appreciated!

I tested with the token you give me (https://braintree-sample-merchant.herokuapp.com/client_token), but still getting same problem (Error: Error requesting one time payment). Please, how can I print the error I'm getting since that come from Native code I think ?

Thanks,
Saad.

**Comment by ShaBax** [comment]
write your code within a try-catch block 
```
try {
 //// request
} catch (error) {
     console.log('error'+JSON.stringify(error));
 }
```

**Comment by Openappdev** [comment]
@ShaBax It's working now! was missing to stringify the error to get the relavent info. Really appreciated! Could not make it without your help :)

**Comment by alapanerao** [comment]
I was getting the same error. But managed to resolved by this solution : https://github.com/smarkets/react-native-paypal/issues/10#issuecomment-635281813
