### ISSUE TITLE
Setting up a payment

### ISSUE THREAD

**Issue by addu1** [smarkets/react-native-paypal#3]
Hey @smarkets i'm trying to integrate your library in my RN project.
Can you help me with what should be passed in the nonce and payerId fields.
Do i need to get them from the UI. If yes what and how should they be fetched.

![screen shot 2018-12-12 at 10 47 02 am](https://user-images.githubusercontent.com/17162834/49848550-96989200-fdfb-11e8-8e68-a8236663b6f3.png)

**Comment by riso** [comment]
hey, sorry for my late reply here. nonce and payerId are provided by PayPal / Braintree SDK. 

Nonce and payerId are fields that returned by the the call to requestOneTimePayment, you don't need to supply these. If you look at the page linked in the readme (https://developers.braintreepayments.com/start/hello-client/ios/v3#get-a-client-token) you will need to send this data to your server component to complete the payment.

Let me know if this helps.

**Comment by riso** [comment]
Closing this, feel free to re-open if you still have issues.

**Comment by addu1** [comment]
I'm taken to this page even on getting a client token from my server  using Braintree Sandbox.
Am i missing something? 

![screen shot 2019-01-02 at 3 47 26 pm](https://user-images.githubusercontent.com/17162834/50587985-0b646680-0ea6-11e9-834c-1267418ca28d.png)

**Comment by riso** [comment]
Could you please share what options object are you passing to the call to `requestOneTimePayment`?

Also, is that the only stack trace you get back when using the production environment? It indicates that your request is being rejected by the Braintree SDK / PayPal, but there should be details of the error coming with that message.

**Comment by addu1** [comment]
Also I'm Using Braintree (4.20.2).

**Comment by riso** [comment]
The Braintree SDK version should be fine, I just completed a payment successfully against our production environment with that version. I'm unable to test with USD but I doubt that would cause any issue.

I think your setup on the server side might be incorrect / incomplete. Could you double check the documentation here https://developers.braintreepayments.com/start/go-live/ ?
Also, with regards to the error that you receive when using production, that happens immediately on the call to `requestOneTimePayment`, i.e. you don't see any PayPal screen? Would you be able to add a breakpoint and see if more information is contained in the error returned?

**Comment by addu1** [comment]
Thank you for the hint. I had an incomplete setup on the Braintree account. Works fine now. :)

**Comment by addu1** [comment]
Now i get this error when i send the nonce to server for processing:

{"result":{"usBankAccountVerification":null,"creditCardVerification":null,"transaction":null,"subscription":null,"errors":{"allDeepValidationErrors":[{"attribute":"payment_method_nonce","code":"TRANSACTION_PAYMENT_METHOD_NONCE_UNKNOWN","message":"Unknown or expired payment_method_nonce."}],"allValidationErrors":[]},"parameters":{"transaction[amount]":"1.00","transaction[type]":"sale","transaction[options][submit_for_settlement]":"true","transaction[payment_method_nonce]":"bde1de23-156a-022c-7e99-eaaeba60d8f9"},"message":"Unknown or expired payment_method_nonce.","target":null,"success":false}}

**Comment by riso** [comment]
Are you regenerating a payment nonce on your server side for every transaction? Those are not supposed to be re-used.

**Comment by addu1** [comment]
No. Generating new nonce on client for every transaction and  sending the same to server

**Comment by riso** [comment]
Are you sending the returned nonce immediately after you receive it? 

Looking at [PayPal doc](https://developers.braintreepayments.com/reference/general/validation-errors/all/#code-93108) it seems like this error is returned when the token is expired or non existent, but in your case it obviously exists. It says there that tokens are only valid for three hours.

**Comment by riso** [comment]
Closing this again, assuming you've sorted it out.

**Comment by Kpglow** [comment]
I'm having trouble implementing the part where I'm supposed to send the nonce to the server component to confirm the current transaction similar to the setting? 
https://developers.braintreepayments.com/start/hello-client/ios/v3#get-a-client-token, gives us an idea of how to integrate the solution onto native applications but I'm not very familiar with how to get this working on my rn application.

**Comment by ducvn95** [comment]
> Thank you for the hint. I had an incomplete setup on the Braintree account. Works fine now. :)

Sorry. I have the same issue. Can you tell me what your incomplete setup is?

**Comment by krupalikevadiya** [comment]
> Thank you for the hint. I had an incomplete setup on the Braintree account. Works fine now. :)

I have same issue..Please tell me what set up is incomplete.
