### ISSUE TITLE
Could not invoke RNPaypal.requestOneTimePayment

### ISSUE THREAD

**Issue by ajaykumar97** [smarkets/react-native-paypal#30]
I am trying to implement `react-native-paypal` but when I call `requestOneTimePayment` method, I am getting error message like: ``Could not invoke RNPaypal.requestOneTimePayment``

My dependencies:

```
"react": "16.9.0"
"react-native": "0.61.5"
"react-native-paypal": "2.1.0"
```

**Comment by riso** [comment]
Could you please provide more details?

1. Which OS are you using?
1. Have you followed the steps of the readme, and if so, could you post the content of your URL schemes for iOS and merged Android manifest for Android?

**Comment by ajaykumar97** [comment]
Sure @riso 

1. OS: Android
2. Yes, I have followed the steps of the Readme. In the readme, There is not any mentioning about adding something in the Android manifest.

**Comment by riso** [comment]
yeah, you shouldn't need to change anything in your android manifest, it should be automatically updated. Could you still post the content of it though?

Here's (https://github.com/smarkets/react-native-paypal/issues/14#issuecomment-493059370) instructions on how to view your merged manifest in Android Studio.

**Comment by ajaykumar97** [comment]
Sure!

![Screenshot 2020-02-19 at 5 34 49 PM](https://user-images.githubusercontent.com/38132295/74832810-2742fa00-533e-11ea-8341-8a405362a571.png)

**Comment by riso** [comment]
Assuming that your applicationId is `com.baseProject.beault` that should be fine. 

Could you please also post the contents of MainApplication.java and build.gradle files?

Also, I'm assuming you've already done this, but could you try again after having cleaned and rebuilt the gradle project and node_modules?

**Comment by ajaykumar97** [comment]
@riso  The error was resolved after removing ``node_module`` folder and reinstalling node modules by running ``yarn`` and clearing npm cache by running command ``npm start -- --reset-cache`` .

Thanks for your time and assistance.
