### ISSUE TITLE
type error :null is not objeckt RnpayPel.requestOneTimePayment

### ISSUE THREAD

**Issue by YOEL311** [smarkets/react-native-paypal#31]
I am trying to implement react-native-paypal but when I call requestOneTimePayment method, I am getting error message like:
type error :null is not objeckt RnpayPel.requestOneTimePayment

![image](https://user-images.githubusercontent.com/39925212/79076079-ecd35900-7cff-11ea-9d2b-f94ccc406d2d.png)

  "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-paypal": "^2.1.0",

OS: Android

 I have followed the steps of the Readme. In the readme

 my manifest 
![image](https://user-images.githubusercontent.com/39925212/79076152-653a1a00-7d00-11ea-91c7-297fb777c092.png)

**Comment by jothikannan** [comment]
@YOEL311 how you fixed this issue?
