### ISSUE TITLE
PROBLEM WITH INSTALLATION

### ISSUE THREAD

**Issue by mica83** [smarkets/react-native-paypal#33]
Hi, i have an issue with installation.

**After this step:**
[iOS] Add pod 'Braintree' to your Podfile and run pod install. If you want, you can specify a version, e.g. pod 'Braintree', '~> 4.19.0'.

I execute command pod install but i have this error:

**[!] No podspec found for `RNPaypal` in `../node_modules/react-native-paypal`**

This is my PodFile

  pod 'RNPaypal', :path => '../node_modules/react-native-paypal'

  pod 'Braintree'

**Comment by mitjnextt** [comment]
Any update on this issue? Have you resolved it? @mica83

**Comment by nzankich** [comment]
@mica83 

1. I would set the Braintree pod to the suggested 4.19.0 version to ensure compatibility (I've created a ticket to update to latest)
`pod 'Braintree', '~> 4.19.0'`

2. are you sure that the package exists in your node_modules?
 try `cat node_modules/react-native-paypal/ios/RNPaypal.podspec` from your project root
don't forget you need to run `yarn` or `npm install` (depending on your package manager) before installing your pods

**Comment by IrvingGuerra** [comment]
The path must be  '../node_modules/react-native-paypal/ios' in ur Podfile

**Comment by nzankich** [comment]
ah, you're right @IrvingGuerra.  That's probably the issue
Try changing your podspec location
`pod 'RNPaypal', :path => '../node_modules/react-native-paypal/ios'`

The podspec is currently in a non standard place.  I'll merge in a fix for it

**Comment by nzankich** [comment]
The latest version (3.0.1) should now auto link correctly
