### ISSUE TITLE
3DS Payment?

### ISSUE THREAD

**Issue by 0x01Brain** [smarkets/react-native-paypal#34]
does this library support 3DS payment?

**Comment by nzankich** [comment]
Hi @0x01Brain ,
This library supports 3DS v1 but needs to be updated to support v2.  I've created a ticket to update https://github.com/smarkets/react-native-paypal/issues/41


There is a guide here about integration https://developers.braintreepayments.com/guides/3d-secure/legacy-3d-secure/configuration
note this part: 
"In production, 3D Secure is not automatically enabled in production accounts and is only compatible with certain Braintree configurations in specific regions. Contact us if you're interested in 3D Secure. We can help determine if you can use 3D Secure and if so, enable your production account."
