### ISSUE TITLE
Problem with paypal login

### ISSUE THREAD

**Issue by mica83** [smarkets/react-native-paypal#35]
Hi, i have an issue when i proceed with authentication.

The errore message is "information isn't correct" but the credential are correct!

I'm in sandbox environment

![Simulator Screen Shot - iPhone 11 - 2020-06-26 at 12 36 58](https://user-images.githubusercontent.com/19794899/85848714-ebb3b300-b7a9-11ea-94ee-9171d2c0026c.png)

**Comment by MZabih** [comment]
@mica83 Have you resolved this issue ? I am facing this issue on live environment.
