### ISSUE TITLE
-canOpenURL: failed for URL: "com.venmo.touch.v2:

### ISSUE THREAD

**Issue by addu1** [smarkets/react-native-paypal#5]
The library works on ios simulators, but when i run it on a real device and also create archive i get this error:

-canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "This app is not allowed to query for scheme com.venmo.touch.v2"

Warning: Attempt to present <SFSafariViewController: 0x15fe3c90> on <RNPaypal: 0x15f9f4f0> whose view is not in the window hierarchy!

**Comment by riso** [comment]
hmm as far as I can tell this should only be a warning that you can ignore. do you actually see this error as a RedBox screen? if not, does anything happen when you tap the button?

**Comment by addu1** [comment]
On clicking the button the dialog for permission should appear and then on accepting it should navigate to paypal. But this doesn't happen in release version or on real device.

**Comment by addu1** [comment]
> hmm as far as I can tell this should only be a warning that you can ignore. do you actually see this error as a RedBox screen? if not, does anything happen when you tap the button?

if you see the logs i have shared it suggests that its an error and not a warning
 **error: "This app is not allowed to query for scheme com.venmo.touch.v2"**

**Comment by nar213** [comment]
@addu1, have you investigated LSApplicationQueriesSchemes?

https://stackoverflow.com/questions/32870393/canopenurl-this-app-is-not-allowed-to-query-for-scheme-instragram

**Comment by addu1** [comment]
> @addu1, have you investigated LSApplicationQueriesSchemes?
> 
> https://stackoverflow.com/questions/32870393/canopenurl-this-app-is-not-allowed-to-query-for-scheme-instragram

should i do something like this ?

`if([[url scheme] isEqualToString:'com.venmo.touch.v2']){

      return [[RNPaypal sharedInstance] application:application
                                        openURL:url
                                        sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                        annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];


    
      return [RCTLinkingManager application:application openURL:url
                          sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey] annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
      }
  
`

If yes, then i have tried doing this. It only removes the error but doesn't move anywhere.

**Comment by riso** [comment]
I don't think that your problem is that message, we see that message in our iOS application as well and we've been using this plugin in our production app for a while.

You see that message because the braintree library can handle things other than PayPal but those features are not supported by the library and therefore you can just ignore that message.

Unfortunately I believe your problem lies in how you're integrating the library or maybe in how you set up your PayPal merchant account, but without having access to your code and your test devices is hard to tell. 
On top of that we don't provide this kind of support so I'm afraid I won't be able to further help you. I'll leave the issue open in case someone else has / had a similar problem and they might be able to help you better.

**Comment by addu1** [comment]
I have multiple URLs in the url handler of Appdelegate. Do you think this might be causing a problem on real device?

**Comment by riso** [comment]
this is what we currently have for our own URL handling logic.

```

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  BOOL isPayPalDeeplink = [[RNPaypal sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  if (isPayPalDeeplink) {
    return isPayPalDeeplink;
  }
  
  return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}

```

It's this way because PayPal URL handling needs to take precedence over whatever else URL handling you have. I don't see why it would behave differently between a simulator and a real device though.

**Comment by NaveenVj16** [comment]
> I have multiple URLs in the url handler of Appdelegate. Do you think this might be causing a problem on real device?

![Uploading Screenshot 2020-06-15 at 8.23.34 PM.png…]()

I got the same error so when checked the Manage PayPal Disputes in the Braintree Control Panel

It started working normally So Just try this one to check it out...

**Comment by alapanerao** [comment]
I was also getting same error for iOS 14. But the with this error I was also getting "Error requesting one time payment"
I managed to resolve with this solution : https://github.com/smarkets/react-native-paypal/issues/10#issuecomment-635281813
