### ISSUE TITLE
Manual installation iOS

### ISSUE THREAD

**Issue by adeel111** [smarkets/react-native-paypal#50]
Having Problems with this part of configuration, it's confusing.

<img width="738" alt="Screenshot 2020-09-11 at 12 11 14 PM" src="https://user-images.githubusercontent.com/31220802/92880997-fcc6a480-f427-11ea-8448-34a0914a1150.png">

1. What kind of files should be added in Libraries folder under project folder and how?

2. From where I can get RNPaypal.xcodeproj so that I could add it under node_modules ➜ react-native-paypal

3. Done

4. Under Build Settings where following path should be added $(SRCROOT)/../node_modules/react-native-paypal/ios

Is it necessary to do Manual installation iOS?

**Comment by nzankich** [comment]
@adeel111 Manually linking libraries on ios isn't very straightforward and I highly suggest going with the auto linking method

That being said, react-native has a pretty nice guide with pictures that may help you out with manual linking https://reactnative.dev/docs/linking-libraries-ios

**Comment by nzankich** [comment]
Let me know if you're still having issues and I can reopen
