### ISSUE TITLE
App crashes with no error on iOS

### ISSUE THREAD

**Issue by wahaj-47** [smarkets/react-native-paypal#51]
App crashed when I clicked proceed with sandbox purchase.

![Simulator Screen Shot - iPhone 11 - 2020-09-18 at 17 16 59](https://user-images.githubusercontent.com/8758774/93596475-38082c80-f96e-11ea-99a2-72c090ccdca0.png)

I get this on the Xcode console

`2020-09-18 17:16:47.619043-0700 vitGroceryShop[11217:175626] -canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "This app is not allowed to query for scheme com.venmo.touch.v2"
2020-09-18 17:16:49.632071-0700 vitGroceryShop[11217:175626] ClientMetadataID: EC-HERMES-SANDBOX-EC-TOKEN
2020-09-18 17:16:50.296588-0700 vitGroceryShop[11217:177593] PayPal-Debug-Id is b9720555ca484
2020-09-18 17:16:50.563816-0700 vitGroceryShop[11217:176209] [AXRuntimeCommon] Unknown client: vitGroceryShop
2020-09-18 17:17:52.211927-0700 vitGroceryShop[11217:175626] -[NSNull length]: unrecognized selector sent to instance 0x7fff8062d9d0
2020-09-18 17:17:52.294588-0700 vitGroceryShop[11217:175626] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff8062d9d0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5dc34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e4190c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e43bf8 _CF_forwarding_prep_0 + 120
	5   vitGroceryShop                      0x00000001097f1898 +[PPOTCore isValidURLAction:] + 488
	6   vitGroceryShop                      0x00000001097f0ecb +[PPOTCore canParseURL:sourceApplication:] + 171
	7   vitGroceryShop                      0x000000010973252a +[BTPayPalDriver canHandleAppSwitchReturnURL:sourceApplication:] + 122
	8   vitGroceryShop                      0x00000001096f7712 -[BTAppSwitch handleOpenURL:sourceApplication:] + 418
	9   vitGroceryShop                      0x00000001096f7401 +[BTAppSwitch handleOpenURL:sourceApplication:] + 129
	10  vitGroceryShop                      0x000000010972e235 __39-[BTPayPalDriver performSwitchRequest:]_block_invoke + 565
	11  SafariServices                      0x00007fff2b97af1f -[SFAuthenticationSession safariViewController:hostApplicationOpenURL:] + 114
	12  SafariServices                      0x00007fff2b9c2766 -[SFAuthenticationViewController remoteViewController:hostApplicationOpenURL:] + 93
	13  SafariServices                      0x00007fff2ba135b3 -[SFBrowserRemoteViewController willOpenURLInHostApplication:] + 68
	14  CoreFoundation                      0x00007fff23e43e8c __invoking___ + 140
	15  CoreFoundation                      0x00007fff23e41071 -[NSInvocation invoke] + 321
	16  libdispatch.dylib                   0x000000011042ee8e _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000110431da2 _dispatch_block_invoke_direct + 300
	18  FrontBoardServices                  0x00007fff36cf86e9 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	19  FrontBoardServices                  0x00007fff36cf83d7 -[FBSSerialQueue _queue_performNextIfPossible] + 441
	20  FrontBoardServices                  0x00007fff36cf88e6 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	21  CoreFoundation                      0x00007fff23da0d31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff23da0c5c __CFRunLoopDoSource0 + 76
	23  CoreFoundation                      0x00007fff23da0434 __CFRunLoopDoSources0 + 180
	24  CoreFoundation                      0x00007fff23d9b02e __CFRunLoopRun + 974
	25  CoreFoundation                      0x00007fff23d9a944 CFRunLoopRunSpecific + 404
	26  GraphicsServices                    0x00007fff38ba6c1a GSEventRunModal + 139
	27  UIKitCore                           0x00007fff48c8b9ec UIApplicationMain + 1605
	28  vitGroceryShop                      0x0000000109574e10 main + 112
	29  libdyld.dylib                       0x00007fff51a231fd start + 1
	30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by nzankich** [comment]
@wahaj-47 I'm going to shoot to try and make an example app to add to this repository to do some additional testing.  I'll see if I can reproduce this

**Comment by nzankich** [comment]
I wasn't able to reproduce this when testing

Which version of ios was this?

Could you see if this solution works for you? https://stackoverflow.com/a/32870555/836366
According to the react-native documentation
```
    /**
     * Determine whether or not an installed app can handle a given URL.
     * NOTE: For web URLs, the protocol ("http://", "https://") must be set accordingly!
     * NOTE: As of iOS 9, your app needs to provide the LSApplicationQueriesSchemes key inside Info.plist.
     * @param URL the URL to open
     */
    canOpenURL(url: string): Promise<boolean>;
```

It's possible that you may need to update your plist file

**Comment by wahaj-47** [comment]
I switched to REST api. I'll try again with the updated plist and test this out.

**Comment by nzankich** [comment]
If anyone experiences this issue again tag me and I can reopen.  I can't reproduce
