### ISSUE TITLE
Your app is using an unsafe implementation of HostnameVerifier.

### ISSUE THREAD

**Issue by shea12** [smarkets/react-native-paypal#52]
We received a security warning "Your app is using an unsafe implementation of HostnameVerifier" from Google Play after submitting a build yesterday. The error seems to be originating in the Braintree Android SDK used by this package.

There is [an open issue](https://github.com/braintree/braintree_android/issues/312) on the [braintree android sdk repo](https://github.com/braintree/braintree_android) relating to this warning. The maintainer suggested that the latest braintree android sdk `v3.14.0` be used.
The current react-native-paypal release `v2.2.0` is targeting braintree `v2.17.0`. At this point it is unclear if updating to `v3.14.0` will fix the security issue but the braintree android sdk version in this package ought to be updated anyhow.

When will this package be updated to use the latest braintree android sdk? This is a critical issue for us. 

Thanks in advance.

**Comment by shea12** [comment]
Updating to braintree android sdk `v3.14.0` does fix the security issue. When can we expect a new release of this package with the updated sdk?

**Comment by nzankich** [comment]
@shea12 I'm sorry for the horribly slow reply.  Just bumped version to latest master
