### ISSUE TITLE
valid token from your server

### ISSUE THREAD

**Issue by weingenious72** [smarkets/react-native-paypal#53]
in the usage section, I show the line to create client token for Braintree. I checked the Braintree document and don't understand where am I going to put the code for getting the client token.

**Comment by nzankich** [comment]
Yea, these instructions are a bit ambiguous currently.  Going to try and create an example app to give more troubleshooting information

**Comment by nzankich** [comment]
@weingenious72 ok, I've updated the readme about how to find/generating this token

The fetch should go immediately before `requestOneTimePayment` or `requestBillingAgreement`.  Wait for the fetch to complete then use the returned token in the react-native-paypal package function

Does that answer your question?

**Comment by nzankich** [comment]
@weingenious72 going to close this.  lmk if you're still having trouble after looking at the readme
