### ISSUE TITLE
Transaction problems in Sandbox Accounts

### ISSUE THREAD

**Issue by cimasala2017** [smarkets/react-native-paypal#59]
I have a problem when making a payment, at the end it performs everything successfully (I have the data of nonce, payerId, email, firstName, lastName, phone) but the money is not discounted in the Sandbox account, I already made all the configurations and I have not had no errors

I want to know if I need an extra configuration in paypal, braintree or react native

**Comment by nzankich** [comment]
@cimasala2017 are you using that nonce on your server to actually make the transaction call?

This package handles most of this these steps: https://developers.braintreepayments.com/start/hello-client/javascript/v3

You then need to send the nonce and payment info from your app to the server and actually make the transaction: https://developers.braintreepayments.com/start/hello-server/ruby#receive-a-payment-method-nonce-from-your-client

**Comment by cimasala2017** [comment]
Greetings, I have another question, when I create the transaction on the server:

TransactionRequest request = new TransactionRequest ()
   .amount (new BigDecimal ("10.00"))
   .paymentMethodNonce (nonceFromTheClient)
   .deviceData (deviceDataFromTheClient)
   .options ()
     .submitForSettlement (true)
     .done ();

Result <Transaction> result = gateway.transaction (). Sale (request);

As I get "deviceDataFromTheClient" from client (react native), I am starting on this and I am not clear about some things, thanks for your help.

**Comment by nzankich** [comment]
In our code we use the Braintree gateway to make the payment requests (instead of `TransactionRequest`)

copying from https://developers.braintreepayments.com/start/hello-server/node
```
gateway.transaction.sale({
  amount: "10.00",
  paymentMethodNonce: nonceFromTheClient,
  deviceData: deviceDataFromTheClient,
  options: {
    submitForSettlement: true
  }
}, (err, result) => {
});
```

**Comment by nzankich** [comment]
I didn't implement the backend portion of our project so I don't know how much I can help here

**Comment by nzankich** [comment]
@cimasala2017 lmk if you are having more issues with this package after implementing your backend
