### ISSUE TITLE
ANDROID: minSdkVersion error - 21

### ISSUE THREAD

**Issue by friendsitsol** [smarkets/react-native-paypal#60]
Reproduce:

1. Created a new react native application using npx command. 
2. Install this plugin using: npm install react-native-paypal --save
3. Follow all the instructions.

Error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:react-native-paypal] /Users/apple/Desktop/react/paypal/node_modules/react-native-paypal/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.smarkets.paypal" to force usage (may lead to runtime failures)

App dependencies:  

"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-paypal": "^3.1.1"
  }

Can you guys help me out on this ?

**Comment by rehmankhalil1001** [comment]
+1 Same issue here!

**Comment by nzankich** [comment]
Could you check your `build.gradle` file?  I think default for a new react-native app is 16 but it needs to be 21 for this package

https://github.com/smarkets/react-native-paypal/blob/master/paypalExample/android/build.gradle

**Comment by friendsitsol** [comment]
@nzankich Yes it was written at 16, i changed it to 21 and started getting this error:
Also changed:
Old build.gradle: classpath("com.android.tools.build:gradle:3.5.3")
New: classpath("com.android.tools.build:gradle:3.6.3")

And it build successfully.
