### ISSUE TITLE
Transaction is not reflecting in both Merchant and Payer

### ISSUE THREAD

**Issue by ericksondelacruz** [smarkets/react-native-paypal#64]
I got the response with no error but the transaction is not reflecting in both Merchant and Payer transaction history. The requestOneTimePayment return the details of the Payer. Email, first name, last name, nonce, and playerId. But when I tried to view both of sandbox account there is no history of transaction happened.

```
requestOneTimePayment( 
  'TOKEN', 
  { 
    amount: '5', 
    currency: 'USD', 
    localeCode: 'en_US', 
    shippingAddressRequired: false, 
    userAction: 'commit', 
    intent: 'sale', 
  } 
)
```

Already tried to transact using Paypal, VISA, and bank account.

**Comment by nzankich** [comment]
@ericksondelacruz are you processing your transaction on your server?  this package is only for creating a nonce token.  You then need to send that to your server and process it there

https://developers.braintreepayments.com/start/hello-server/ruby

**Comment by ericksondelacruz** [comment]
@nzankich oh that make sense.

Thank you, it is already working!
