### ISSUE TITLE
requestOneTimePayment send me to following page.

### ISSUE THREAD

**Issue by krupalikevadiya** [smarkets/react-native-paypal#66]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-12-26 at 15 29 35](https://user-images.githubusercontent.com/69295445/103149420-23ca8d00-471e-11eb-8e98-6762b185bcd4.png)

**Comment by nzankich** [comment]
@krupalikevadiya you are using your sandbox token right?  This is expected

**Comment by krupalikevadiya** [comment]
Yes i'm using sendbox token.But what if i want to test payment? 
It is only worked with production?
