### ISSUE TITLE
 Error: Exception in HostObject::get(propName:RNPaypal): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment;

### ISSUE THREAD

**Issue by shashitechvalens** [smarkets/react-native-paypal#68]
Error: Exception in HostObject::get(propName:RNPaypal): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment;

**Comment by nzankich** [comment]
@shashitechvalens make sure you have followed step 2 of the setup instructions

```
[Android] Add implementation "com.braintreepayments.api:braintree:3.14.1" in android/app/build.gradle. 
```

**Comment by nzankich** [comment]
going to close this as a duplicate of https://github.com/smarkets/react-native-paypal/issues/22

if you're still having issues tag me in there and I can reopen that one
