### ISSUE TITLE
Attempt to present <SFSafariViewController: 0x18e63a60> on <RNPaypal: 0x18e632b0> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by kotomono** [smarkets/react-native-paypal#7]
on physical device calling requestOneTimePayment doesn't show up the paypal page and log this error on the console.

on the emulator it works.

**Comment by riso** [comment]
Hello @kotomono, do you still have the same issue? IIRC you can ignore that warning, but I'm not sure at the moment. If you still have issues with that, would you mind sharing your `AppDelegate.m` code?
