### ISSUE TITLE
Transaction Not Reflecting in sandbox account .

### ISSUE THREAD

**Issue by SaqibNytro** [smarkets/react-native-paypal#71]
I have followed other questions and downgraded react-native-paypal@2.1.0 . still doesn't sees paypal payment is done(PROMPT) . but now i am getting response in promise(payerId , nonce , payer email .. etc ) not getting transactionId in response.But , on opening the sandbox account i am unable to see any transaction record done over there.

@nzankich

**Comment by nzankich** [comment]
@SaqibNytro in order to see your transaction record you'll need to implement your backend.  I've added some steps to the readme.

Can you look at the example app and see if you're getting your expected responses?

**Comment by nzankich** [comment]
v 4.1.0 includes a server side implementation example. Check that out and lmk if you're still having issues
