### ISSUE TITLE
Migrating to new version 

### ISSUE THREAD

**Issue by sr7354476** [smarkets/react-native-paypal#77]
Migrating to new version that is 4.0.1 receiving following  error in android and ios both
 "btdatacollector.h' file not found in react native"

**Comment by nzankich** [comment]
Hey @sr7354476 

Make sure to follow the upgrade instruction steps:
https://github.com/smarkets/react-native-paypal/releases/tag/4.0.0

**Comment by nzankich** [comment]
Tag me if you're still seeing issues

**Comment by rr180enovate** [comment]
> Hey @sr7354476
> 
> Make sure to follow the upgrade instruction steps: https://github.com/smarkets/react-native-paypal/releases/tag/4.0.0

Thank you 
Working fine
