### ISSUE TITLE
Does this library provide any login/authorization codes?

### ISSUE THREAD

**Issue by haveamission** [smarkets/react-native-paypal#81]
Sorry if this is vaguely off topic, but I've been trying to find information on this for like a week now.

I'm trying to update an app from the old mobile SDKs to the new SDKs.

The client wants to pay users out money when they complete offers, which seems like it might need something like the payouts API.

But I need to get things like Payer ID (or maybe an authorization code) to do that. Can this app do any of that? Or is it just for checkout only?

**Comment by nzankich** [comment]
@haveamission hmm, I wasn't the one that added the paypal vaulting but you do get payer id from that.  I think it's purpose is for subscriptions so not sure how it would would work for client -> user payments

From the docs:
```
// For vaulting paypal account see: https://developers.braintreepayments.com/guides/paypal/vault
const {
	nonce,
	payerId,
	email,
	firstName,
	lastName,
	phone
} = await requestBillingAgreement(
  token,
  {
    billingAgreementDescription: 'Your agreement description', // required
    // any PayPal supported currency (see here: https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments)
    currency: 'GBP',
    // any PayPal supported locale (see here: https://braintree.github.io/braintree_ios/Classes/BTPayPalRequest.html#/c:objc(cs)BTPayPalRequest(py)localeCode)
    localeCode: 'en_GB',
  }
);
```

Maybe try that out?  I'm curious to hear your findings

**Comment by haveamission** [comment]
Yeah, I think what I actually need is the Connect with PayPal setup, and that seems to have to be setup differently (there doesn't appear to be any sort of native SDKs for it, and certainly no RN library, so I'm writing a custom implementation).

Thanks for your help!
